### ISSUE TITLE
Can we specify more than one versions?

### ISSUE THREAD

**Issue by GoldenMouse** [heroku/heroku-buildpack-python#1105]
We would like both py 2.8 and py 3.6. Can we specify more than one version to be installed using this buildpack?

**Comment by edmorley** [comment]
@GoldenMouse Hi! Unfortunately that's not possible, and is something that we probably won't want to support, since the UX starts to get tricky (for example: Does the same requirements.txt get used for both? What version should `pip` with no version call? Which of the Python bin dirs get put on path first, so will "win" when it comes to pip package bin wrappers? etc).

If you need a different Python version for something like running a quick script, I would use system Python from the stack image. (You will likely need to unset PYTHONPATH and PYTHONHOME for system Python to work; something that's on my list to avoid the need for in the future.)

**Comment by edmorley** [comment]
Closing as wontfix due to the above.
