### ISSUE TITLE
Update PYTHONPATH inside post_compile hook

### ISSUE THREAD

**Issue by rmaceissoft** [heroku/heroku-buildpack-python#1172]
I'm trying to compile `.po` files into `.mo` during the post_compile hook. See the script below:

```
#!/usr/bin/env bash

echo "-----> Debugging post-compile hook"

echo "PYTHONPATH=$PYTHONPATH"
export PYTHONPATH=/app/project
echo "PYTHONPATH=$PYTHONPATH"

python manage.py compilemessages -l es
```

However the following error is raised and seems like the reason is that manage.py doesn't recognize that _PYTHONPATH_ was updated

```
remote: -----> Running post-compile hook
remote: -----> Debugging post-compile hook
remote: PYTHONPATH=/app/project
remote: PYTHONPATH=/app/project
remote: /app/.heroku/python/lib/python3.6/site-packages/environ/environ.py:639: UserWarning: Error reading /tmp/build_cc51ec34/.env - if you're not configuring your environment separately, check this.
remote:   "environment separately, check this." % env_file)
remote: Traceback (most recent call last):
remote:   File "manage.py", line 22, in <module>
remote:     main()
remote:   File "manage.py", line 18, in main
remote:     execute_from_command_line(sys.argv)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
remote:     utility.execute()
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
remote:     django.setup()
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
remote:     apps.populate(settings.INSTALLED_APPS)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
remote:     app_config = AppConfig.create(entry)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/apps/config.py", line 116, in create
remote:     mod = import_module(mod_path)
remote:   File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
remote:     return _bootstrap._gcd_import(name[level:], package, level)
remote:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
remote:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
remote:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
remote: ModuleNotFoundError: No module named 'app'
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to poli-helper.
remote: 
```

Due to the project structure I'm using, _PYTHON_PATH_ needs to point to `/app/project` and I can confirm that it works out of the `post_compile` hook via a config var (`heroku config:set PYTHONPATH=/app/project`)

Appreciate if someone can confirm that what I'm trying to do is possible and make sense and what could be missing here.

### buildpacks used 
```
$ heroku buildpacks
=== XXXXX Buildpack URLs
1. https://github.com/masamitsu-murase/heroku-buildpack-gettext.git
2. https://github.com/moneymeets/python-poetry-buildpack.git
3. heroku/python
```

**Comment by edmorley** [comment]
@rmaceissoft Hi! Currently builds on Heroku are performed in the directory `/tmp/build_<hash>` rather than `/app`. At the end of the build the contents of the `/tmp/build_<hash>` directory are archived and uploaded as the slug, then at runtime this slug is downloaded to `/app` on the dynos.

For many languages, the runtimes/tooling don't need to worry about the location of files changing, since they handle relocation fine. For Python this used to be very much not the case, and whilst newer versions of Python have improved the auto-detection of things like where Python is located, there are still lots of things that can break. This is why the Python buildpack does a symlink + set `PYTHONHOME` trick, along with rewriting the `.pth` files for editable installs:
https://github.com/heroku/heroku-buildpack-python/blob/b78b514f52a621abf28b1ca8f2bf6f2492bd5595/bin/compile#L239-L249
https://github.com/heroku/heroku-buildpack-python/blob/b78b514f52a621abf28b1ca8f2bf6f2492bd5595/bin/compile#L269-L273
etc

That is to say, the `/app` does not contain your app's source code, only a symlink from `/app/.heroku/...` to the equivalent build directory paths.

As such I would imagine your error isn't due to `PYTHONPATH` not being updated - but instead because during the build it should actually be set to something like `/tmp/build_<hash>/project`, not a path under `/app`.

I would update your `bin/post_compile` to derive the correct path from the location of `bin/post_compile`.

> Due to the project structure I'm using, PYTHON_PATH needs to point to ...

Are you using one of the subdir buildpacks? If so, which one?

**Comment by rmaceissoft** [comment]
@edmorley 
thanks to not trying to debug with `echo $PWD` I have received your so much masterful answer 
Everything makes perfect sense to me now. Below the final version of my post_compile script:
```
#!/usr/bin/env bash

export PYTHONPATH="$BUILD_DIR/project"
python manage.py compilemessages -l es
```

also, thx for pointing the `subdir buildpacks` idea, but my project structure doesn't fit with that

I'm closing this issue now,

thank so much!

**Comment by edmorley** [comment]
You're welcome! :-)
