### ISSUE TITLE
Support for pip constraint files

### ISSUE THREAD

**Issue by GuillaumeDesforges** [heroku/heroku-buildpack-python#1177]
To improve reproducibility, one can use constraint files with pip.

This is required for airflow for instance: https://airflow.apache.org/docs/apache-airflow/stable/installation.html#constraints-files
Currently there seems to be no way of specifying a constraint file using this buildpack.

**Comment by edmorley** [comment]
@GuillaumeDesforges Hi! Thank you for raising this :-)

The reason Airflow uses constraint files is:

> Airflow installation might be sometimes tricky because Airflow is a bit of both a library and application. Libraries usually keep their dependencies open and applications usually pin them, but we should do neither and both at the same time.

Heroku applications fall under "application" rather than "library", so should ideally be pinning their dependency versions for determinism.

That is to say - the Airflow constraints file is a means to dynamically generate a "working" set of dependency versions, however IMO once that list of dependency versions has been calculated, it should be committed to `requirements.txt` in the repo, and then Heroku, CI, and any other tooling (for example Dependabot automatic dependency updates) work on `requirements.txt` and not a constraints file.

ie:

```
$ CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"
$ pip install "apache-airflow==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"
$ pip freeze > requirements.txt
$ git commit -am 'Update Airflow'
$ git push heroku main
```

Are there specific use-cases you had in mind that explicitly can't (or don't want) to pin dependencies in `requirements.txt`?

**Comment by GuillaumeDesforges** [comment]
Hi @edmorley , thank for the complete yet reactive answer.

I think I'll write a `prefreeze-requirements.txt`, do pip install from it then freeze to requirements.txt as suggested.

Guess that closes this.

**Comment by eric-gravyty** [comment]
Hi @edmorley, I'm wondering if you can consider reopening this feature request?

Particularly for larger projects, it would be nice to have an easy way of separating the concerns of direct dependency management and transitive dependency management.

I think in terms of implementation, it could be relatively simple, something like this to replace https://github.com/heroku/heroku-buildpack-python/blob/20e198b957238f78f21ad7a5a909edcbd9e1a353/bin/steps/pip-install#L31:
```bash
    INSTALL_ARGS=(-r "$BUILD_DIR/requirements.txt" --exists-action=w --src=/app/.heroku/src --disable-pip-version-check --no-cache-dir --progress-bar off)
    if [ -f "$BUILD_DIR/constraints.txt" ]; then
        INSTALL_ARGS=(${INSTALL_ARGS[@]} -c "$BUILD_DIR/constraints.txt")
    fi
    /app/.heroku/python/bin/pip install ${INSTALL_ARGS[@]} 2>&1 | tee "$WARNINGS_LOG" | cleanup | indent
```


> Are there specific use-cases you had in mind that explicitly can't (or don't want) to pin dependencies in `requirements.txt`?

My particular use case is that our project has additional requirements in development environments that we don't want in deployed environments (particularly `django-sslserver`), which means that developers can't just mindlessly run `pip freeze > requirements.txt`. Additionally, our requirements file for production is currently 255 lines long, as it includes both direct and transitive dependencies. This creates a decent amount of extra work for developers each time they update dependencies, as they need to compare the `pip freeze` output to the existing file and run `pip show <package>` to trace up from every added dependency to ensure that what they're adding to our production requirements is something that's actually needed. And when we need to *remove* a dependency it's even worse: a developer needs to manually go through each of the removed dependency's dependencies (and possibly their dependencies, etc) to see of those can be safely removed, as a simple `wipeenv && pip install -r requirements.txt -c constraints.txt` won't work while they're still in requirements.txt.

Allowing us to keep our `requirements.txt` slimmer by keeping it to just direct dependencies while still being able to put constraints on indirect dependency versions in `constraints.txt` would be great for dev efficiency. Using the standard `constraints.txt` file instead of having a bespoke process where we put direct dependencies in `requirements-prefreeze.txt` will help reduce friction when onboarding new team members.

**Comment by edmorley** [comment]
@eric-gravyty Hi! I still don't believe we should support constraints files. Short term something like https://github.com/jazzband/pip-tools/ sounds like it would help your use-case. Longer term I would suggest using Poetry support (once the buildpack supports it natively).
