### ISSUE TITLE
Django collectstatic not running

### ISSUE THREAD

**Issue by nlarusstone** [heroku/heroku-buildpack-python#1201]
I have a Django app deployed on Heroku, but the `python manage.py collectstatic --noinput` command never seems to run. I manually ran `heroku run python manage.py collectstatic --noinput` successfully, but I want it to run as part of my build step.

Here's the last part of my Heroku logs:
```
Successfully installed Django-3.1.1 ...
-----> Discovering process types
       Procfile declares types -> web, worker
-----> Compressing...
       Done: 184.1M
-----> Launching...
       Released v140
```

**Comment by edmorley** [comment]
Hi! The logic for determining whether to run collectstatic is here:
https://github.com/heroku/heroku-buildpack-python/blob/f7157a8ee67183a58e4be1deae0c6a8120aed456/bin/steps/collectstatic#L17-L27

And is tested (so should be working):
https://github.com/heroku/heroku-buildpack-python/blob/f7157a8ee67183a58e4be1deae0c6a8120aed456/spec/hatchet/django_spec.rb#L32-L35

I would guess the most likely cause is that `DISABLE_COLLECTSTATIC` is set in the app's config vars.

If that isn't the reason, please open a support ticket so that permission to view the app in question can be granted.

Many thanks :-)
