### ISSUE TITLE
TimedOut Running BuildPack Python

### ISSUE THREAD

**Issue by Akhil-Tony** [heroku/heroku-buildpack-python#1232]
when i'm trying to deploy i always get this error after running for 30 mins

![Screenshot (11)](https://user-images.githubusercontent.com/72643926/129518179-496d2fd0-6dbc-41f1-a89a-dc9f07598db9.png)

**Comment by edmorley** [comment]
@Akhil-Tony Hi! For support requests please open a ticket at http://help.heroku.com since the GitHub issues here are not as regularly monitored, and are for bugs rather than support issues.

In this case it looks like your app is using an old version of Pandas that does not have a wheel available for Python 3.9 (hence why it's having to compile wheels from source, which takes much longer). Upgrade the dependencies to newer versions and they will come with already-compiled wheels compatible with Python 3.9.

If you are hosting your code on GitHub, I'd recommend Dependabot to automate keeping your dependencies up to date:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates
