### ISSUE TITLE
More tolerant runtime.txt parsing so Heroku can co-exist with CloudFlare Pages / Netlify monorepos

### ISSUE THREAD

**Issue by cmdlinebeep** [heroku/heroku-buildpack-python#1243]
Hello @edmorley  I am running into a similar issue with CloudFlare Pages (JAMstack) that you originally filed here:
https://github.com/netlify/build-image/issues/141

Namely, that I am using a monorepo where our backend is on Heroku and our frontend is on CloudFlare Pages (which is using the same runtime.txt format from Netlify).  Due to Heroku using a different runtime.txt format than these other platforms, I can't use this monorepo for both.  I @'ed you in the comments over on that other ticket, but it's probably better to file new here.  

This is now blocking me to the point I'm looking into switching to CloudFlare Workers instead of the worker process I currently have deployed to Heroku, to keep from maintaining two, non-DRY repos.

It would be awesome, and seems straightforward, if Heroku could just support any of these formats:

```
X.Y.Z
python-X.Y   or
python-X.Y.Z
```

in the runtime.txt file.  

I see there are some other ideas proposed of passing things in a Yaml or JSON file, but those look like heavier lifts than what I'm proposing.  If the runtime.txt parser can just strip out the `X.Y.Z` data from the runtime.txt, then prepend `python-` back on the front, both platforms can easily be supported today with no other changes and breaking no existing deployments.

Here is the regexp, can this please be supported?  🙏

`/(\d+\.\d+(\.\d+)?)/`

I tested this at regexr.com. Thanks!

**Comment by edmorley** [comment]
@cmdlinebeep Hi! There was some previous discussion about supporting alternative formats in `runtime.txt` in #913, where I was considering the idea.

However thinking about it more, it feels slightly wrong to be putting a Python-specific version string with only the version (and not the fact it's Python) in a file named `runtime.txt`, since it's a generic filename. ie: If the file had originally been called `python-runtime.txt`, then fair enough, but `runtime.txt` could be for any language. 

As such, it seems to make more sense to adjust Netlify's parsing instead - ie: make a 1 line change - to make any `python-` prefix be stripped using using bash string substitution.

ie: Replace:
https://github.com/netlify/build-image/blob/fa439ad1ab9393b2c0d449d8d7c033927683f4b0/run-build-functions.sh#L225

With:

```bash
    PYTHON_VERSION=$(cat runtime.txt)
    # Remove any `python-` prefix from the version string.
    PYTHON_VERSION="${PYTHON_VERSION#python-}"
```

I don't know if something similar could be done for CloudFlare (is there repo open source?).

The `runtime.txt` concept also only existed (as far as I know) for Heroku+Python, not in any other ecosystems, so it's puzzling that both Netlify and CloudFlare have copied this (vendor-specific + suboptimal method that we would like to drop at some point) approach, but yet chosen an incompatible contents for the file?

**Comment by cmdlinebeep** [comment]
@edmorley Hi Ed, thanks for your reply.  

Maybe Heroku can be a leader in having a more tolerant `runtime.txt` parser and the others will copy this new method as well.  ;-)

I get what you're saying about having just the numbers in that file could be less clear, but it would only be for people like me who changed it to support a Netlify / CloudFlare monorepo that works with Heroku as well.  i.e. People who know what they're doing.  To be clear, I'm not proposing that _any_ platform change the expected or typical format of their file.  So most people would still have the `python-` prefix in there and would know no different.

I'm simply proposing that the Heroku parser can be more flexible in understanding any `runtime.txt` contents with one minor change.  One could argue that Netlify / CloudFlare should change theirs instead, since Heroku came first.  But honestly, being more flexible in accepting inputs is just _better_ (no matter who came first).  Additionally, I happen to have the Python Heroku person "on the phone," as it were, who has experienced this issue first-hand, so I assumed getting a fix into Heroku fix this would be the easier way to go.  :-)

I'm essentially saying that the Heroku parser can pull the `X.Y` or `X.Y.Z` out of the `runtime.txt` file, and then add the `python-` back on to the beginning for its own internal use.  That way people who don't need a monorepo with CloudFlare or Netlify can still keep `python-` in their `runtime.txt` files.  Those that need to support a monorepo can remove the `python-` prefix, and in this case the advanced users know what they are doing.  But no one needs to change their `runtime.txt` files at all, and I'm not asking Heroku or anybody to change the expected format. 

For what it's worth, I've also searched around and I don't believe CloudFlare Pages build environment is open sourced (just the docs).

**Comment by edmorley** [comment]
> Maybe Heroku can be a leader in having a more tolerant `runtime.txt` parser

I understand what you're saying, however "be a leader" to me means "be the first one to do the right thing". However in this case, adding support for a less logical syntax doesn't seem like the right thing. The existing format has also been around longer.

**Comment by cmdlinebeep** [comment]
Hi Ed.  I'm sure you are well intentioned, but that's really disappointing to hear when the "right thing" solution (issue #913) doesn't look like it's had any action in over a year.  Is something still happening on that ticket?

Meanwhile, this is a real problem for users, and it just seems like Heroku doesn't want to take on work to play nice with other vendors, mostly because they came first.  I get that, but it also seems like a "fake because" when a better solution doesn't appear to be in the works.

Anyway, thanks for your time and take care.

**Comment by edmorley** [comment]
I don't think that's a fair summary of the situation.

What I'm saying in this issue, is that actually, adding support for `X.Y.Z` syntax in `runtime.txt` is not the right thing, since it's not a Python specific file. Therefore, any version string in that file should say the language to which it's referring. 

This buildpack already supports that approach, so is already "doing the right thing", and there isn't any "better solution in the works". This isn't about trying to avoid playing nicely with other vendors just because this approach was first, it's because this approach makes more sense, and also there are a great number more of repositories our there using this format.

Longer term I would love to deprecate `runtime.txt` support, and replace it with something more native to the Python ecosystem (for example `pyproject.toml`). However that will need to come after I finish the Python [Cloud Native Buildpack](https://buildpacks.io/), which is set to replace this buildpack entirely in the future.
