### ISSUE TITLE
setuptools <49.0.0 does not handle Python 3.10 correctly in `python_version` environment markers

### ISSUE THREAD

**Issue by sileht** [heroku/heroku-buildpack-python#1248]
The newly added `python 3.10` doesn't work with pip 20 and setuptools 47

old pip/setuptools version thinks python 3.10 is python 3.1:
* https://bugs.python.org/issue42744
* https://github.com/pypa/pip/issues/6730
* https://github.com/python/cpython/pull/24386

Python 3.10 requires pip>=21 and setuptools>=52 (https://github.com/python/cpython/blob/3.10/Lib/ensurepip/__init__.py)

**Comment by edmorley** [comment]
@sileht Hi! Thank you for opening an issue :-)

The Python buildpack doesn't use `ensurepip` to install the versions of Pip or setuptools in the build for a few reasons, and instead installs the version of Pip/setuptools defined here:
https://github.com/heroku/heroku-buildpack-python/blob/ec2fd784fdfe7c6b5da79ad8bdbcfaecb7d7fe23/bin/steps/python#L153-L167

We're currently using Pip 20.2.4 since it's the last release before the new resolver became the default, and there are still several compatibility issues that make upgrading to newer pip painful (more in #1109). Thankfully the upcoming Pip 21.3 release (due within days, though we will want to wait for any dust to settle) resolves the most significant of those, so we should be good to update soon.

For setuptools, we're currently using 47.1.1, since 47.2.0 and newer are affected by #1006. The long term fix for that is changing the way the build system works, so that the directory in which builds occur is the same as that which is used at runtime. However doing that breaks some other buildpacks, so is not a quick change (and that work has had to be put on hold).

Re Python 3.10 specifically, do you have some examples of things that are failing currently using the above pip/setuptools versions?

Our CI is currently passing, and the pip issue linked in the issue description was fixed in pip 19.3, so shouldn't affect Python 3.10 usage on Heroku.

Many thanks :-)

**Comment by sileht** [comment]
I setup a tiny project that reproduces the issue, too, but it looks like you just beat me  😛

https://github.com/sileht/heroku-py3.10-bug

Anyways, upgrading setuptools, workaround the issue.
