### ISSUE TITLE
v210's upgraded setuptools no longer supports `use_2to3`

### ISSUE THREAD

**Issue by ddarren** [heroku/heroku-buildpack-python#1312]
Looks like my build (deploy to Heroku) is failing with:

```
remote:        [pipenv.exceptions.InstallError]:   error in visionLiveSDK3 setup command: use_2to3 is invalid.
```

The library with `use_2to3` does not have an upgraded verson yet. I'm not a python programmer and I'm not sure if the last buildpack upgrade was meant to deprecate `use_2to3` or not. I'm going to try using the previous buildpack version.

See https://stackoverflow.com/questions/69100275/error-while-downloading-the-requirements-using-pip-install-setup-command-use-2 for a dicussion on `setuptools ` and `use_2to3`

**Comment by edmorley** [comment]
@ddarren Hi! Thank you for opening an issue.

This error is unfortunately expected for packages that are still using the `use_2to3` feature.

The upstream setuptools project has removed support for the `use_2to3` feature, since it's been deprecated for some time:
https://github.com/pypa/setuptools/pull/2731

This removal was released in setuptools 58.0.0 on 2021-09-04.

We're not in control of what the Python packaging ecosystem chooses to deprecate/remove support for, however have attempted to reduce the impact by continuing to use an older setuptools version in this buildpack until now, in order to give extra time for packages and app dependency trees to be fixed.

However, it's no longer possible to hold off updating setuptools any longer, because we need to use a newer version of setuptools to resolve a different set of issues users are encountering (import errors when using Pipenv and packages that pull in newer setuptools as a transitive dependency).

For now, if affected packages do not have fixed versions, I would recommend:
1. Reporting the issue to whomever maintains the package
2. Pinning to the previous buildpack version as a temporary workaround (this is best not done long term)

The `visionLiveSDK3` package mentioned in the error message doesn't appear to exist on https://pypi.org - however googling I found:
https://github.com/Granicus/visionLiveSDK-Python3

I would open an issue here:
https://github.com/Granicus/visionLiveSDK-Python3/issues

The fix will be removing this one line:
https://github.com/Granicus/visionLiveSDK-Python3/blob/d9514940ffeb82acf99ea2de23e7b2c0fa05c2e2/setup.py#L37
(and checking it still works without the 2to3 tool rewriting the code)

If the maintainer of that package ends up not responding, another option would be to fork that repository, delete the one line, and then update your `Pipfile` to point at your fork, rather than the original repository.

Hope that helps!

**Comment by edmorley** [comment]
(Hope you don't mind - I've shortened the issue title, since I've pinned this issue and GitHub's UI was eliding the second and most important half of the title on the issues overview page)

**Comment by ddarren** [comment]
@edmorley Thanks for all the detail! Currently, I deployed with the previous version of the buildpack which worked. I also opened an issue for the visionsdk library https://github.com/Granicus/visionLiveSDK-Python3/issues/1 - If they don't update, then I'll just do a fork.

**Comment by edmorley** [comment]
Closing since this is working as expected / is an upstream issue.
