### ISSUE TITLE
Is the python package cache invalidated if a sub-requirements file were changed?

### ISSUE THREAD

**Issue by luzfcb** [heroku/heroku-buildpack-python#1316]
I have the following structure:

```
project_root/
    Procfile
    runtime.txt
    manage.py
    requirements.txt
    requirements/
            base.txt
            test.txt
            dev.txt
            heroku.txt
```

The `requirements.txt` content is:
```
# All the requirements are in requirements/ directory separated by environment.
# This file only exists because Heroku search for a requirements.txt file
# to install the dependencies.
-r requirements/heroku.txt
```

The `requirements/heroku.txt` content is:

```
-r base.txt

gunicorn==20.1.0
whitenoise==6.0.0
```
Question: Is the python package cache invalidated if a sub-requirements file (`heroku.txt` or `base.txt`) were changed?

**Comment by edmorley** [comment]
@luzfcb Hi! No at present changes to sub-requirements files don't result in cache invalidation, meaning the things like uninstalled packages will only get cleaned up on Python version change or stack change, if the root requirements.txt is not updated itself.

**Comment by luzfcb** [comment]
@edmorley there is possible to update the documentation and explicitly explain when the Python package cache will be invalidated and when is not, like my question?

**Comment by luzfcb** [comment]
@edmorley there is any environment variable that I can use to control the cache behavior and turn off the Python package cache?

**Comment by edmorley** [comment]
@luzfcb Great points! :-)

In the new Python Cloud Native Buildpack that is due to replace this buildpack in the future, I'm planning on adjusting caching behaviour slightly, as well as making what's happening easier to understand (eg via build log output explaining when it reuses vs discards the cache). My preference is to make the buildpack easy enough to understand that the amount of separate documentation required is reduced.

Re turning the cache off, there isn't currently an env var for that, but the `bin/pre_compile` or `bin/post_compile` hooks could be used to manually delete/adjust the cache. 

Could you explain more about the issue you are encountering?
