### ISSUE TITLE
upgrade to stack heroku-22 using python version 3.6.7.  is it possible?

### ISSUE THREAD

**Issue by maxi-89** [heroku/heroku-buildpack-python#1380]
Hello community, I have an application that works with python version 3.6.7 on the heroku-18 stack. 
Is it possible to upgrade to heroku-22 stack and add a runtime.txt file with python-3.6.7? so that my application still works?

**Comment by edmorley** [comment]
Hi!

Python 3.6 reached end of life upstream on 2021-12-23:
https://devguide.python.org/versions/#unsupported-versions

This means there are no new versions of it being released, so no security or bug fixes. As such, it's currently insecure to use, since the various security issues found in Python since 2021-12-23 will only have been fixed in newer Python major versions (Python 3.7+). 

This is mentioned in the build logs of any Heroku-18 app that is using Python 3.6:

```
remote:  !     Python 3.6 reached upstream end-of-life on December 23rd, 2021, and is
remote:  !     therefore no longer receiving security updates:
remote:  !     https://devguide.python.org/versions/#supported-versions
remote:  !     
remote:  !     Upgrade to a newer Python version as soon as possible to keep your app secure.
remote:  !     See: https://devcenter.heroku.com/articles/python-runtimes
```

End of life Python versions are not made available for newer Heroku stacks due to the security issues with them mentioned above, plus also often older Python versions won't even compile on newer stacks without extra work anyway (for example due to them requiring older OpenSSL that is no longer available).

You will need to update to one of the supported Python versions documented here:
https://devcenter.heroku.com/articles/python-support#supported-runtimes

As an added bonus, newer Python versions typically come with performance improvements, so your app will often run faster too.
