### ISSUE TITLE
Problem trying to deploy in heroku-22 anyjson setup command: use_2to3 is invalid.

### ISSUE THREAD

**Issue by maxi-89** [heroku/heroku-buildpack-python#1381]
im trying to miigrate my app from heroku-18 stack to heroku-22 stack but i have had some problems. in my local enviroment ir runs... but when i try to deploy in heroku from gitlab its as the version of setuptools was harcoded. 

```
eploying application
uploading application archive
triggering new deployment
-----> Building on the Heroku-22 stack
-----> Using buildpack: heroku/python
-----> Python app detected
-----> Using Python version specified in runtime.txt
-----> Installing python-3.9.15
-----> Installing pip 22.2.2, setuptools 63.4.3 and wheel 0.37.1
-----> Installing SQLite3
-----> Installing requirements with pip
```
.....

```
Collecting anyjson>=0.3.3
         Downloading anyjson-0.3.3.tar.gz (8.3 kB)
         Preparing metadata (setup.py): started
         Preparing metadata (setup.py): finished with status 'error'
         error: subprocess-exited-with-error
         
         × python setup.py egg_info did not run successfully.
         │ exit code: 1
         ╰─> [1 lines of output]
             error in anyjson setup command: use_2to3 is invalid.
             [end of output]
         
         note: This error originates from a subprocess, and is likely not a problem with pip.
       error: metadata-generation-failed
       
       × Encountered error while generating package metadata.
       ╰─> See above for output.
       
       note: This is an issue with the package mentioned above, not pip.
       hint: See above for details.
 !     Push rejected, failed to compile Python app.
 !     Push failed
heroku build still pending
Already up to date.
HEAD detached at 14fafe9
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.pip-cache/
nothing added to commit but untracked files present (use "git add" to track)
deploy failed
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

**Comment by edmorley** [comment]
Hi

This is unfortunately working as expected.

The `anyjson` package uses the deprecated `use_2to3` feature in its `setup.py`, which is no longer supported as of setuptools v58+ (this setuptools version was released over a year ago):
https://setuptools.pypa.io/en/stable/history.html#v58-0-0

The best fix here would be for the `anyjson` package to remove the use of `use_2to3` from its `setup.py`, however the package is seemingly unmaintained, as it has not had a release since June 2012 (https://pypi.org/project/anyjson/#history) and the project homepage URL on PyPI even 404s.

If your app itself directly uses `anyjson`, then the solution would be to switch to either the Python stdlib `json` module, or else one of the other third party JSON libraries such as [orjson](https://pypi.org/project/orjson/).

However, another common reason your app is depending on `anyjson` might be if your app is using Celery, and is on a very old Celery version, such as Celery 3 (which via its `kombu` dependency transitively depends on `anyjson`).

If old Celery is the case here, you will need to update to Celery v4.0 or higher (which uses Kombu 4+, which no longer has the `anyjson` dependency):
https://docs.celeryq.dev/en/stable/history/whatsnew-4.0.html#upgrading-from-celery-3-1

It's worth noting that Celery 4.0 was released in November 2016, so even this is still a very old version.

**Comment by edmorley** [comment]
Closing since this is an issue with the `anyjson` package, that hasn't been maintained for 10 years.

Your options are to either:
- (Recommended) Stop using `anyjson` (potentially by updating to newer Celery/Kombu, if that's the reason for the dependency on it).
- Generate a wheel manually for `anyjson` locally using an older setuptools version, and vendor that `.whl` file in your repository (and reference the file instead of the normal anyjson requirements specifier in your `requirements.txt`). For example steps, see: https://github.com/pypa/setuptools/issues/2788#issuecomment-921962154 (just skip the upload part and use the file locally instead).
- Pin to the last Python buildpack release that used an older setuptools (v209), using the buildpack URL syntax documented here: https://devcenter.heroku.com/articles/buildpacks#buildpack-references . However this is not recommended, since you won't receive other buildpack fixes/changes, and so will encounter other issues in the future.
