### ISSUE TITLE
pipenv cache is skipped when it should not be

### ISSUE THREAD

**Issue by niespodd** [heroku/heroku-buildpack-python#1398]
This will silently make the buildpack skip cache when a project relies on or uses anything that relies on package(s) having `git` in its name:
https://github.com/heroku/heroku-buildpack-python/blob/051987161254aa6b709a1706db79b12fce354295/bin/steps/pipenv#L13

A good example is:
* [streamlit](https://streamlit.io/) which has `gitpython` as a dependency and seems to be widely used,
* [GitPython](https://github.com/gitpython-developers/GitPython),
* [gitdb](https://github.com/gitpython-developers/gitdb),
* and [other hundreds of packages](https://pypi.org/search/?q=git).

While I understand why the buildpack is checking for `git`, this should be handled differently:
* force skip install should be behind an environment flag, given most of the users will not depend on packages installed from `git+://`
* this check should look for `"ref": ` or `"git": ` string(s)
* or, given lock references a particular commit hash, this check should not exist at all.

But most importantly **this buildpack should notify the user why install was enforced**.

**Comment by edmorley** [comment]
Hi! Thank you for filing an issue - I agree the current pipenv caching handling here is broken.

So thinking about this a bit, I'm leaning towards treating lockfiles as deterministic (since well, that's the whole point of them), and not having any forced-invalidation behaviour in the buildpack at all for this. It would then be up to Pipenv to ensure it puts deterministic things in the lockfile (and not eg a branch name without a corresponding SHA). 

Pipenv might very well do that already - however, I don't use Pipenv, and I haven't had a chance to play around with this. And even if Pipenv doesn't lock to a SHA in the lockfile, well that kind of seems like a bug that's up to Pipenv to fix - and so something that we shouldn't work around in the buildpack here.

Thoughts?

**Comment by edmorley** [comment]
Though it seems there were issues for editable mode, xref:
https://github.com/heroku/heroku-buildpack-python/pull/1130#issuecomment-815942296

As such, it's this would need further research before we can change this.

**Comment by edmorley** [comment]
The fragile `git` check has been removed as of #1526. The `pipenv install` step is now run every time, however, this doesn't mean the cache isn't used. The `site-packages` directory is still cached - it will just now be up to Pipenv to determine whether the environment needs updating, or whether the install step can no-op.
