### ISSUE TITLE
Can I change the python source?

### ISSUE THREAD

**Issue by YixinSong-e** [heroku/heroku-buildpack-python#1428]
When I use 
`pack build custom_model:v1 --builder=heroku/builder:22`
The error output:
`Details: https://heroku-buildpack-python.s3.us-east-1.amazonaws.com/heroku-22/runtimes/python-3.9.16.tar.gz: Dns Failed: resolve dns name 'heroku-buildpack-python.s3.us-east-1.amazonaws.com:443': failed to lookup address information: Try again`

**Comment by edmorley** [comment]
Hi

The repo for the Python CNB is https://github.com/heroku/buildpacks-python rather than https://github.com/heroku/heroku-buildpack-python.

However, your issue is not a problem with the CNB, but instead a local networking/firewall/proxy issue, that we're not able to do anything about.

Please check your network/firefox/proxy settings :-)
