### ISSUE TITLE
Value of DISABLE_COLLECTSTATIC not used?

### ISSUE THREAD

**Issue by peterfarrell** [heroku/heroku-buildpack-python#179]
It appears that even if you set `DISABLE_COLLECTSTATIC=0` that the buildpack continues to not run `collectstatic`.  The only way I've found to go back is to remove the config var entirely using `heroku config:remove DISABLE_COLLECTSTATIC`.

It seems counter intuitive that it is only looking for the mere existence of `DISABLE_COLLECTSTATIC` to determine if `collectstatic` is disabled.

Shouldn't this check the value of `DISABLE_COLLECTSTATIC` as well?

**Comment by kennethreitz** [comment]
This is a pretty common bash-ism.

**Comment by maestrofjp** [comment]
I realize it's a common bash-ism, but it's caught a few of my developers off because they thought it looked like it would act like boolean and therefore thought it would work that way. I'm sure that we're not the only people that have been caught off guard by it.

The reason I brought it up is that while it's bash under the hood -- it's not evident to think it's bash from the Heroku CLI or if you use the config vars section in the dashboard.  So nobody was thinking about the underlying implementation of the buildpack but from the PoV of what seemed reasonable on what it looks like it should do.

I'm speaking from an usability stand point without the actual implementation in mind (i.e. bash).  We only figured out the issue because we had to read the source code for the buildpack.  I'm sure most people don't go that far.

I'd still say the README should at least document this behavior because most probably aren't thinking it's bash under the hood and I'm willing to write something if you will accept a PR for doco.

That's my two cents...thanks for the consideration anyways.
