### ISSUE TITLE
Django i18n support (compilemessages)

### ISSUE THREAD

**Issue by caiofbpa** [heroku/heroku-buildpack-python#198]
Currently we have to commit .mo files in Django in order to have the production environment working with i18n, and that sucks a lot. The ideal way would be to commit only the .po files and have the buildpack compile them into .mo files for us.
When I have some spare time I can try to work on a pull request for this.

**Comment by xblitz** [comment]
+1 for this!

**Comment by milest** [comment]
+1

**Comment by rnazrati** [comment]
+1

**Comment by DeathBorn** [comment]
+1

**Comment by xblitz** [comment]
any reason for closing this ticket without commenting?

**Comment by eillarra** [comment]
+1

**Comment by edmorley** [comment]
it's worth noting that you can add arbitrary commands to `bin/post_compile` (which albeit is undocumented) which are run near the end of the compile step:
https://github.com/heroku/heroku-buildpack-python/blob/v77/bin/compile#L230

That said, running compilemessages in a dyno created with this buildpack currently fails with:
```bash
~ $ ./manage.py compilemessages
CommandError: Can't find msgfmt. Make sure you have GNU gettext tools 0.15 or newer installed.
```

Googling found this post_compile file which installs the missing dependency and then runs compilemessages, which you could use for reference in your own projects:
https://github.com/stefanw/froide/blob/4cf78328939ce2387304085a402f130c5cf5c5f0/bin/post_compile#L13-L47

**Comment by RobertAKARobin** [comment]
@ken-reitz Why was this closed?

**Comment by edmorley** [comment]
Reopening this issue to remind me to take another look at it, once I get a chance to triage the open issues in this repo :-)

**Comment by zerazobz** [comment]
> it's worth noting that you can add arbitrary commands to `bin/post_compile` (which albeit is undocumented) which are run near the end of the compile step: https://github.com/heroku/heroku-buildpack-python/blob/v77/bin/compile#L230
> 
> ~That said, running compilemessages in a dyno created with this buildpack currently fails with:~
> 
> ```shell
> ~ $ ./manage.py compilemessages
> CommandError: Can't find msgfmt. Make sure you have GNU gettext tools 0.15 or newer installed.
> ```
> 
> ~Googling found this post_compile file which installs the missing dependency and then runs compilemessages, which you could use for reference in your own projects: https://github.com/stefanw/froide/blob/4cf78328939ce2387304085a402f130c5cf5c5f0/bin/post_compile#L13-L47~
> 
> Edit: Since this post, the `gettext` package has been added to the Heroku stack images (in [heroku/stack-images/pull/90](https://github.com/heroku/stack-images/pull/90)), so it's no longer necessary to install gettext manually. Just add `./manage.py compilemessages` to a `bin/post_compile` in your app, and the Python buildpack will run it towards the end of the buildpack compile.

@edmorley I tried to follow your advice.
I went to Settings -> Commands

And inside "Build Command"  I put: *./manage.py compile messages*
Then the build log throws me the following:

_[2023-04-21 04:31:21] │ Running custom build command: ./manage.py compilemessages
[2023-04-21 04:31:21] │ bash: ./manage.py: Permission denied
[2023-04-21 04:31:21] │ building: exit status 126
[2023-04-21 04:31:21] │ ERROR: failed to build: exit status 1_

**Comment by edmorley** [comment]
> I went to Settings -> Commands
> Inside "Build Command" I put: ./manage.py compile messages

This sounds like the settings in your IDE. These are not settings for Heroku.
The previous comments are referring to `bin/post_compile`, a file you need to create within your application source code.

**Comment by zerazobz** [comment]
My mistake.
I come from Digital Ocean, they said they are using `heroku-buildpack-python` as build pack.
In Digital Ocean App / Settings / Commands, I ended up adding the compile command as follows:

`django-admin compilemessages`

And this time it works well.

**Comment by edmorley** [comment]
Revisiting this, I don't think this is a feature that we should add to the Python buildpack directly, since:
- As of Jan 2018, the Heroku stack images now include the `gettext` package needed for `compilemessages`, so there is no custom setup required.
- The current Python buildpack already supports running arbitrary commands after the build (via the `bin/post_compile` feature mentioned above), so generating translations is a matter of adding a single file that calls the `django-admin compilemessages` command.
- Only a small subset of Django apps use the translations feature, so if we try to run the command automatically, at best it will unnecessarily slow down the build for most Django apps, and at worst it will cause build errors, or confusion when we output warnings or errors for apps that have a misconfigured translations configuration (since they don't use the feature). (This contrasts to the `collectstatic` feature, where virtually all Django apps will need to run it, and not running it can result in hard to debug 404s etc.)
- As such, we probably wouldn't want to enable the buildpack feature by default, at which point having to set an env var or config option is not much less effort than having to create the `bin/post_compile` file.
- The `compilemessages` command several CLI arguments that some users may need to customise (https://docs.djangoproject.com/en/4.2/ref/django-admin/#compilemessages), at which point they couldn't use the automatic feature anyway.
