### ISSUE TITLE
Advanced Django Detection

### ISSUE THREAD

**Issue by kennethreitz** [heroku/heroku-buildpack-python#209]
Currently, the buildpack just checks for a `manage.py` file before proceeding with Collectstatic support. Now that we have advanced `requirements.txt` detection, it would be much better to also check for Django as a dependency.

**Comment by antonagestam** [comment]
@kennethreitz Wouldn't you still need `manage.py` to run `collectstatic`?

**Comment by kennethreitz** [comment]
Nothing will change about the usage of `manage.py`... we just won't attempt to run collectstatic if Django isn't a dependency.

**Comment by blueyed** [comment]
@kennethreitz 
> have advanced requirements.txt detection

What detection are you referring to?
The detection of changed dependencies or the file itself?

**Comment by kennethreitz** [comment]
we can now intelligently check to see if a package was requested to be installed

**Comment by cclauss** [comment]
https://github.com/bndr/pipreqsis highlights an interesting trend of auto-generating the `requirements.txt` by doing analytics on a project's import statements.

**Comment by cclauss** [comment]
https://github.com/bndr/pipreqs highlights an interesting trend of auto-generating the `requirements.txt` file by running analytics on the project's import statements.

**Comment by ryanhiebert** [comment]
`manage.py` is a small script, with almost no value. It's sole value is in setting the `DJANGO_SETTINGS_MODULE` environment variable. Otherwise, everything can be done by `django-admin`.

It doesn't mesh well with the general idea of Heroku not liking any environment variables available at build time, but I like the idea of checking if `DJANGO_SETTINGS_MODULE` is in the environment and `Django` is in the requirements, and then just running `django-admin collectstatic`, and not require the `manage.py` at all.

**Comment by kennethreitz** [comment]
`DJANGO_SETTINGS_MODULE` should never need to be set — there should be one and only one settings file for your Django application.

**Comment by ryanhiebert** [comment]
`DJANGO_SETTINGS_MODULE` _is_ required, since we don't know what that settings file is. It just happens that the `manage.py` is where it is typically set. I agree that it shouldn't be required in many Heroku apps, I only present it as a reasonable alternative to having a `manage.py` in the repository.

I also don't think that in the general case there should be one and only one settings file. I haven't personally (yet) had the use for more than one settings file, but I can imagine a scenario where the same repository would have multiple settings files for the primary purpose of having a different configuration of sub-apps installed and available to the user. I've actually contemplated this eventuality for a particular project that I'm working on, I just don't need it yet.

My point is that since the `DJANGO_SETTINGS_MODULE` **must** be set somewhere, whether `manage.py` or the environment, that it would make sense to allow either as a way to specify it.
