### ISSUE TITLE
v64 seems to not include python/bin in PATH

### ISSUE THREAD

**Issue by jhorman** [heroku/heroku-buildpack-python#254]
After deploying this morning, my `/app/.heroku/python/bin/` was no longer in path. Or, I should say, an executable we use on heroku for db migrations `arnold` was no longer available. We rolled back quickly, so I am not sure if `arnold` was not installed properly, or if `bin` was no longer in path. Changing our buildpack back to https://github.com/heroku/heroku-buildpack-python.git#v62 seemed to fix things.

**Comment by jhorman** [comment]
Actually, I believe `gunicorn` also wasn't found, based on the papertrail logs.

**Comment by danvk** [comment]
Thanks for filing this. I was incredibly confused why my new Python Heroku app wasn't working this morning.

Running

    heroku buildpacks:set 'git://github.com/heroku/heroku-buildpack-python.git#v62'

did the trick.

**Comment by santiagomalter** [comment]
I was experiencing the exact same issue... :+1: @danvk 

I think I will always fix the tag in the buildpack urls next time.

**Comment by MrWeeble** [comment]
We also had a problem - we use a multipack which includes the python buildpack, but it appears that if failed to install newrelic from our requirements file. Since newrelic-admin is the command that runs as the web process in the Procfile, this meant that it would not even boot up.

Changing the URL in the .buildpacks file to append '#62' to the python URL resolved this for us.

**Comment by kennethreitz** [comment]
this was reverted almost immediately because of this. There's a new attempt being formed in the `multi` branch, if anyone wants to test!
