### ISSUE TITLE
libxmlsec1 support

### ISSUE THREAD

**Issue by kvarga** [heroku/heroku-buildpack-python#257]
Has anyone got libxmlsec1 to work on heroku cedar-14 with python libraries (dm.xmlsec.binding specifically)?

**Comment by kvarga** [comment]
I updated my code and call xmlsec through Popen instead of using a library like dm.xmlsec.binding . 

I used buildpack: https://github.com/jmorrice/heroku-buildpack-xmlsec 

I'd still like to be able to use a python library for this, but alas, its fixed before cedar-10 is retired.

Closing.

**Comment by jasonpstewart** [comment]
Sorry I'm late to this - we did a multi buildpack with https://github.com/heroku/heroku-buildpack-apt 

with Aptfile that includes: 
```
swig
libxmlsec1-dev
```

Then, we had to modify the python buildpack's bin/compile file to add the apt directories so that pip (swig) would link with the appropriate libraries:

```
# Add heroku-buildpack-apt paths
export PATH=$PATH:/app/.apt/usr/bin
export C_INCLUDE_PATH=$C_INCLUDE_PATH:/app/.apt/usr/include:/app/.apt/usr/include/xmlsec1
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/app/.apt/usr/include:/app/.apt/usr/include/xmlsec1
export INCLUDE_PATH=/app/.apt/usr/include:/app/.apt/usr/include/xmlsec1:$INCLUDE_PATH
export LIBRARY_PATH=$LIBRARY_PATH:/app/.apt/usr/lib/x86_64-linux-gnu:/app/.apt/usr/lib/i386-linux-gnu:/app/.apt/usr/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/app/.apt/usr/lib/x86_64-linux-gnu:/app/.apt/usr/lib/i386-linux-gnu:/app/.apt/usr/lib
# export PYTHONPATH=/app/.apt/usr/lib/python2.7/dist-packages/
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/app/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/app/.apt/usr/lib/i386-linux-gnu/pkgconfig:/app/.apt/usr/lib/pkgconfig
export CPATH=/app/.apt/usr/include:$CPATH
export CPPPATH=/app/.apt/usr/include:$CPPPATH
export SWIG_LIB=/app/.apt/usr/share/swig2.0/
```

Our fork is here: https://github.com/skilljar/heroku-buildpack-python

(I didn't PR this into the main one since it's pretty apt-get / swig 2.0 specific - and was basically just a hack to get it working - I'd rather a more generic compatibility with the buildpack-apt so we don't have to hack around it like we did.
