### ISSUE TITLE
Support for Google ortools

### ISSUE THREAD

**Issue by swanson** [heroku/heroku-buildpack-python#289]
[Google's `ortools`](https://developers.google.com/optimization/) do not work when installed via `pip` directly on Heroku (some issues with native packages it seems: [discussion](https://groups.google.com/forum/#!searchin/or-tools-discuss/python/or-tools-discuss/SPsSC6t1WNI/0Akd1motfdQJ)). This prevents the python buildpack working out of the box with `ortools` in `requirements.txt`.

I've created a fork of this buildpack that adds an [extra step](https://github.com/swanson/heroku-buildpack-python-ortools/blob/master/bin/steps/ortools) to manually install via `setuptools` using this [`setup.py`](https://github.com/swanson/heroku-buildpack-python-ortools/blob/master/vendor/ortools/setup.py). Creating an application with that buildpack works great and I can use the library as expected.

**Questions**
- Is there interest in supporting this package in the main buildpack? I see that some libraries with native extensions or other tricky installations are supported, some are not.
- If so, is the method in the above-mentioned fork acceptable (shelling out to setuptools)? Or does the library need to be installed using pre-built binaries?
- If not, is there a better way to inject the special step for ortools without forking the buildpack? I'd like to avoid having to keep the fork in sync with upstream if possible.

PS: this codebase is very well organized -- I was pleasantly surprised how easy it was to understand and extend. Great work :)

**Comment by edmorley** [comment]
I guess ideally this would be fixed upstream in their setup.py. I know the newsgroup thread states "pypi, setuptools, and pip are just broken", but without tickets filed or more details, I find that hard to believe.

In the meantime, the manual install steps could be performed via the post_compile hook ([example unrelated hook](https://github.com/mozilla/treeherder/blob/master/bin/post_compile)), rather than needing to fork the buildpack perhaps? (Though this wouldn't work if other dependencies in requirements.txt require or-tools, since their install would be attempted prior to post_compile running - and pre_compile is run too soon to be useful).

**Comment by swanson** [comment]
> I guess ideally this would be fixed upstream in their setup.py

I tend to agree -- though I'm not versed enough in the tools to narrow down the problem. I'm just a guy that wants to run some linear optimizations and the Python bindings were the least onerous :)

> via the post_compile hook

Thanks -- this looks great. My use-case does not involve other libraries depending on `ortools` (nor do I think that is a common case) so this should be sufficient. Only small downside would be that I would have to remove `ortools` from `requirements.txt` to prevent `pip` from trying to install it (and failing). 

I found more information here: https://github.com/heroku/heroku-buildpack-python/issues/87 about the hooks.

**Comment by swanson** [comment]
@edmorley The `post_compile` hook worked great! Much easier than a fork and I like that I can keep it with the application code. Thanks!

**Comment by edmorley** [comment]
You're welcome :-)
