### ISSUE TITLE
Writing the elapsed time of the compile step to the log?

### ISSUE THREAD

**Issue by cclauss** [heroku/heroku-buildpack-python#420]
The [compile step](../blob/master/bin/compile) is the key deliverable of this buildpack.  It would be helpful if the last action of the compile step was the write the elapsed time and any activated URL to the main log.  Being exposed to this information on a regular basis would encourage both the developers and the users of the buildpack to optimize its performance.  Writing this info to the log would allow us to understand improvement or degradation over time.  Perhaps this data is captured somewhere [behind the scenes](../blob/master/bin/steps) but putting it in the open would surely spark some innovation around lowering the elapsed time within this effort and many of the projects that depend on it.

**Comment by kennethreitz** [comment]
Thanks for the idea!

**Comment by edmorley** [comment]
@cclauss whilst this issue was more about making buildpack developers aware of the compile time (which I imagine happens via the private metrics Heroku that records now anyway), for end-users I have created a buildpack that prefixes each line of the build logs with timestamps, and adds an overall duration to the end of each buildpack's compile step:
https://github.com/edmorley/heroku-buildpack-timestamps

We're been using it in production for 6 months now and it's helped us track down the slow parts of our multi-buildpack builds (which ended up being mostly the various commands run in  `post_compile`).
