### ISSUE TITLE
/app/.heroku/python/bin/pip: No such file or directory

### ISSUE THREAD

**Issue by codingjoe** [heroku/heroku-buildpack-python#447]
Hi I get this error all of a sudden. Cache is clean, stack is `heroku-16`.

```text
-----> Python app detected
-----> Installing python-3.5.1
-----> Installing pip
-----> Installing requirements with pip
       /app/tmp/buildpacks/779a8bbfbbe7e1b715476c0b23fc63a2103b3e4131eda558669aba8fb5e6e05682419376144189b29beb5dee6d7626b4d3385edb0954bffea6c67d8cf622fd51/bin/steps/pip-install: line 7: /app/.heroku/python/bin/pip: No such file or directory
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by codingjoe** [comment]
Never mind. Only on Python 3.5.1. Once up update to 3.6.2 it works.

**Comment by edmorley** [comment]
I can repro this using a clean cache and the stable `heroku/python` buildpack release (v110).

The issue is that the Python 3.5.1 binary doesn't exist for Heroku-16 (only the more recent runtime versions were built for Heroku 16, the [builds/runtimes/](https://github.com/heroku/heroku-buildpack-python/tree/master/builds/runtimes) directory contains the versions that were built for it):
```
$ curl -sSI https://lang-python.s3.amazonaws.com/heroku-16/runtimes/python-3.5.1.tar.gz | head -n 1
HTTP/1.1 404 Not Found
```

The buildpack should be catching that error and failing early, rather than proceeding to the pip install step.

In fact this is fixed on master, which instead gives the correct error message:
```
remote: -----> Installing python-3.5.1
remote:  !     Requested runtime (python-3.5.1) is not available for this stack (heroku-16).
remote:  !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
```

This is because in v110 the exit code check was broken, but has since been fixed as part of the fixes found using the shellcheck linter:
https://github.com/heroku/heroku-buildpack-python/commit/f74d4db8c5953b39ef69852157ad8f78d678bf8d#diff-57a28f8b2bf70b3efa895ae239e9d986R31

**Comment by mercuree** [comment]
I get same error, when trying to install python-3.5.3.
https://lang-python.s3.amazonaws.com/heroku-16/runtimes/python-3.5.3.tar.gz
File exists
stack heroku-16.

**Comment by edmorley** [comment]
You're issue is likely unrelated, given that the one here was due to the file missing, and the error message in that case has seen been made clearer due to fixes in the buildpack. As such, I'd open a new issue :-)

**Comment by kennethreitz** [comment]
thank you @edmorley
