### ISSUE TITLE
Pull #456 causes  locale lookup failure in 3.6.2 builds

### ISSUE THREAD

**Issue by ian-axelrod** [heroku/heroku-buildpack-python#457]
https://github.com/heroku/heroku-buildpack-python/pull/456's change to stdlib version fetched causes the following error in python 3.6.2 builds:

```

-----> Installing requirements with pip
       Fatal Python error: Py_Initialize: Unable to get the locale encoding
       ModuleNotFoundError: No module named 'encodings'
       
       Current thread 0x00007f6e625f3700 (most recent call first):
       /tmp/stdlib.sh: line 122:  1008 Aborted                 "$@"
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by kennethreitz** [comment]
I actually think this is unrelated. It looks like your Python is broken somehow, by the `heroku config` variables you have set.

**Comment by stevejalim** [comment]
We're having this issue too, when things were fine 4 days ago (before the long weekend). No code changes at our end have happened re runtimes etc. 

Am exploring what the config pain might be now.

FWIW:

`runtime.txt` is:

```
python-3.6.2
```

The only config vars that aren't related to our app are:

```
BUILDPACK_URL:                   https://github.com/heroku/heroku-buildpack-python
LANG:                            en_US.UTF-8
HEROKU_DEPLOY_BRANCH:            dev
LD_LIBRARY_PATH:                 /app/.heroku/vendor/lib
LIBRARY_PATH:                    /app/.heroku/vendor/lib
PATH:                            /app/.heroku/venv/bin:/bin:/usr/local/bin:/usr/bin
PYTHONHOME:                      /app/.heroku/venv/
PYTHONPATH:                      /app/
PYTHONUNBUFFERED:                true
```

**Comment by ian-axelrod** [comment]
We've not made any changes to our python related variables, but I'll investigate more.

**Comment by stevejalim** [comment]
OK, making this change to our Heroku Settings / `heroku config` values fixed it for us: 

`PYTHONHOME:                      /app/.heroku/python/`

(cc @ian-axelrod)

----
I noticed that what we had specced in the config (`/app/.heroku/venv/`) wasn't the same as what was actually exported in a running one-off dyno (`/app/.heroku/python/`) so I updated the config to match and deploys started working again.

`<conjecture>`
My (total) guess is that the running application dynos are getting their `PYTHONHOME` corrected/fixed dynamically (or that it's not being used), but the buildpack is directly getting whatever's been specced via Heroku Settings, which - since a point in time prior to https://github.com/heroku/heroku-buildpack-python/pull/456 - wasn't actually a valid path, but we were getting by somehow.
`</conjecture>`

**Comment by Coalpaw** [comment]
I had the same issue with some apps I inherited.  I made the same change (setting `PYTHONHOME` to `/app/.heroku/python/` from `/app/.heroku/venv/`, along with a corresponding change to the `PATH`).  Curious as to why this stopped working but it does appear that the buildpack prefers `/app/.heroku/python/` event though it used to use `/app/.heroku/venv/`.

**Comment by edmorley** [comment]
I believe the problem is that the custom `sub-env` function previously implemented in this buildpack has been replaced by the buildpack-stdlib's `sub_env` which is actually subtly different in behaviour, as part of #456.

The implementation previously used by this buildpack:
https://github.com/heroku/heroku-buildpack-python/blob/845635d66710d0e37d909c725ced1dbdcb418b60/bin/utils#L56-L78

The buildpack-stdlib implementation:
https://github.com/heroku/buildpack-stdlib/blob/372175219930a292548d88691a37d74bb18426cc/stdlib.sh#L88-L130

Notably the old implementation used to blacklist `PYHONHOME` and `PYHONPATH` - meaning they couldn't be overridden by people's `heroku config` environment variables. I'm presuming the people whose apps are no longer working have these set from the past at legacy values (the buildpack no longer uses `venv` as the directory name).

**Comment by stevejalim** [comment]
@edmorley That would fit with my experience (and also strongly imply that I could just remove PYTHONHOME - and prob PYTHONPATH - from our configs). 👍

**Comment by edmorley** [comment]
Yes - I would try unsetting those from the app configs (after making a note of the previous value in case you need to revert). 

Failing that, as a workaround in the meantime pin to the previous buildpack release (v110 probably your best bet to avoid the grep output warnings spam), following the steps here:
https://devcenter.heroku.com/articles/buildpacks#buildpack-references

...though if you do that, remember to revert it back to the `heroku/python` alias so it tracks the stable releases for the future, unless you wish to bump the version manually from now on.

**Comment by stevejalim** [comment]
I don't think we need to roll back buildpacks - we're able to deploy. I will try `unset`ting those vars later, though

**Comment by ian-axelrod** [comment]
I unset the variables (`PYTHONPATH` and `PYTHONHOME`) and builds work for me now. Greatly appreciated, @stevejalim & @edmorley.

**Comment by kennethreitz** [comment]
Will investigate Blacklisting those variables today.

**Comment by meshy** [comment]
I just had this issue when upgrading from python 2.7 to 3.6.4. Setting `heroku config:set PYTHONHOME=/app/.heroku/python/` fixed it for me. Thank you @stevejalim.
