### ISSUE TITLE
python buildpack erases other vendor files while "clearing cache"

### ISSUE THREAD

**Issue by duanehutchins** [heroku/heroku-buildpack-python#764]
If the stack or SQLite3 changes, this buildpack removes all existing files in `.heroku/vendor` along with other several other directories: https://github.com/heroku/heroku-buildpack-python/blob/d3180d3245d08e2abe9f7bb265e9fd633ea29ae5/bin/steps/python#L49

This breaks installations from other buildpacks which installed into `.heroku/vendor` or another of those removed directories (e.g. https://github.com/cyberdelia/heroku-geo-buildpack/).

These files are erased by this buildpack in order to clear out the cache which itself copied into them during bin/compile: https://github.com/heroku/heroku-buildpack-python/blob/d3180d3245d08e2abe9f7bb265e9fd633ea29ae5/bin/compile#L166

I suggest that instead of copying and then removing the invalid cache files, this buildpack only copies the cache files if cache is valid.

**Comment by pythdasch** [comment]
Hi I'm facing a similar problem, I'm using your Buildpack alongs  https://github.com/cyberdelia/heroku-geo-buildpack

and since 1 week, I cannot build anymore because it says that it doesn't find what installed geo-buildpack.

django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0", "gdal1.11.0", "gdal1.10.0", "gdal1.9.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.

**Comment by duanehutchins** [comment]
@pythdasch Set BUILD_WITH_GEO_LIBRARIES=1, and remove the geo buildpack, and this python buildpack should install those geo libraries for you.

Alternatively, you're welcome to switch your python buildpack to my own github fork, until this repo fixes the bug.

**Comment by CaseyFaist** [comment]
This is not related to the vendoring issue, but for using GEO libraries, recommended way is to use this buildpack: https://github.com/heroku/heroku-geo-buildpack

On to vendoring - I see this issue, this is something we've had a chat or two around whether this should be a buildpack standard (and not just something Python should do) - several other buildpacks handle caches this way, but it's not explicitly required here: https://devcenter.heroku.com/articles/buildpack-api#caching

Can't promise when we'll see movement on this, but am interested in addressing this concern.

**Comment by edmorley** [comment]
So I think the answer here is for buildpacks to avoid using `.heroku/vendor` and instead use a directory namespaced to their use-case. Such as what heroku-geo-buildpack does here:
https://github.com/heroku/heroku-geo-buildpack/blob/510b625ae2bacc9904f7408f1656b89dbf3e1670/bin/compile#L28

That would also mean heroku-buildpack-python should stop using `.heroku/vendor` too -- though very soon (once Cedar-14 support removed, and also the GEOS/GDAL support transitioned to third party buildpacks fully) this buildpack won't have anything left that it vendors in `.heroku/vendor` so can stop using it entirely.

**Comment by edmorley** [comment]
Closing as wontfix, since `.heroku/vendor` has historically been a directory used only by this buildpack. Moving forwards all buildpacks (including this one) should namespace their assets in the cache to avoid overlap. This buildpack will soon no longer need a vendor directory at all (so most references to `.heroku/vendor` here will be removed), however we'll be purging the sqlite3 remnants, which will still mean that directory gets removed for some time.
