### ISSUE TITLE
Bump pipenv version to 2018.11.14

### ISSUE THREAD

**Issue by macbeth322** [heroku/heroku-buildpack-python#786]
There was an issue in pipenv that was causing heroku deployments to fail because not all dependencies were getting installed sometimes. This was fixed in https://github.com/pypa/pipenv/pull/3070 and released in `pipenv==2018.11.14`. Is it possible to bump the version of pipenv that is used by the buildpack so we can get this fix?

**Comment by techalchemy** [comment]
As a sidenote I will be releasing a bugfix release tonight and it may be advantageous to pin that one

FYI this seriously impacts my work builds -- I can't deploy to heroku due to pipenv pinning which is super unfortunate and has been a big annoyance for my team (and a good motivator to get things fixed)

**Comment by jwin742** [comment]
Is there a reason this hasn't been done yet? Seems like it should be a very simple change now that the bug in pipenv has been fixed. Or at least make the version used configurable. 

It's getting kind of annoying for my team and I to be stuck on older versions of pipenv

**Comment by CaseyFaist** [comment]
Hi there! some context:

Unfortunately, the current version of Pipenv would require users to uninstall and reinstall their local pipenv environments before being able to deploy again successfully. This is due to incompatibility with the lock files that is not autocorrected by pipenv's update function. Since this would require coordination between the release and all pipenv users, or would result in a temporarily opt-in upgrade (which, if anyone missed the communications around it, could lead to quite a lot of frustration), we're not looking at this update any time soon.

I am sorry about this frustration, however our version (2018.5.18) is also not as behind the current version (2018.11.26) as it has been since the most recent pipenv release. I'd like to see a bit more stability in the release cycle from the project before prioritizing this issue.

**Comment by nikolaik** [comment]
> I am sorry about this frustration, however our version (2018.5.18) is also not as behind the current version (2018.11.26) as it has been since the most recent pipenv release. I'd like to see a bit more stability in the release cycle from the project before prioritizing this issue.

Hi! pipenv have since your comment received two releases and it's main maintainer has dedicated time set aside for pipenv work by it's employer. Hope to see you reconsider your stance on pipenv upgrades

**Comment by edmorley** [comment]
@nikolaik Hi! Deciding the best way forwards for alternative package manager support (for example, should the buildpack support them natively, or via additional buildpacks; should we add poetry support, what to do with the currently out of date pipenv support etc) is high up my list. Pipenv now having more recent releases is something I will definitely factor into that decision :-)
