### ISSUE TITLE
Travis failling

### ISSUE THREAD

**Issue by AndreGuerra123** [heroku/heroku-buildpack-python#800]
The only means I have to develop this buildpack and perform testing is using TravisCI. I'm trying to implement poetry support.
However, currently, this build is currently failling on TravisCI. Any chance to fix this.
I got:
`The command "bundle exec hatchet ci:setup" failed and exited with 1 during .
`
On the current passing build it seems there is a exit error aswell but it is ignored. What can be the cause of this?
Regards

**Comment by CaseyFaist** [comment]
Since the `master` branch is succeeding, this is something we can talk through and debug in your PR 👍I've left you a few comments there already.

If you have Docker installed, you can run tests locally by running this Make command from the root directory:

`make test` 

You can check out what that's doing by looking at the [Makefile](https://github.com/heroku/heroku-buildpack-python/blob/master/Makefile)
