### ISSUE TITLE
SQLite3 Installation Fails on Cedar-14

### ISSUE THREAD

**Issue by quentinlesceller** [heroku/heroku-buildpack-python#962]
For some reasons (it used to work fine before December 2019), we cannot deploy our app anymore because of a SQLLite3 installation error.

```
git push heroku master
Enumerating objects: 166, done.
Counting objects: 100% (121/121), done.
Delta compression using up to 4 threads
Compressing objects: 100% (67/67), done.
Writing objects: 100% (72/72), 11.97 KiB | 1.50 MiB/s, done.
Total 72 (delta 50), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Python app detected
remote:  !     Python has released a security update! Please consider upgrading to python-3.7.6
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
remote: -----> Found python-3.3.5, removing
remote: -----> Installing python-3.7.1
remote: -----> Installing pip
remote: -----> Installing SQLite3
remote: mv: missing destination file operand after ‘/tmp/build_faba773db88a55454a60db19517a9c72/.heroku/python/include/’
remote: Try 'mv --help' for more information.
remote: mv: missing destination file operand after ‘/tmp/build_faba773db88a55454a60db19517a9c72/.heroku/python/lib/’
remote: Try 'mv --help' for more information.
remote: sed: can't read /tmp/build_faba773db88a55454a60db19517a9c72/.heroku/python/sqlite3/usr/lib/x86_64-linux-gnu/pkgconfig/sqlite3.pc: No such file or directory
remote: mv: missing destination file operand after ‘/tmp/build_faba773db88a55454a60db19517a9c72/.heroku/python/bin/’
remote: Try 'mv --help' for more information.
remote: -----> Installing requirements with pip
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to blockcypher.
remote:
To https://git.heroku.com/blockcypher.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/blockcypher.git'
```

Our app does not require SQLLite3 (our code is here https://github.com/blockcypher/explorer).

I have found some ressource son stackoverflow such as this (one)[https://stackoverflow.com/questions/56677029/heroku-python-app-failing-to-build-when-installing-sqlite3] and even tried with this buildpack https://github.com/heroku/heroku-buildpack-python#remove-sqlite mentioned here.

Our app is running on Cedar-14.

**Comment by quentinlesceller** [comment]
I can confirm that this error is because of Cedar-14. Upgrading your environment will fix it. So the conclusion is that Heroku broke the python environment (although cedar-14 is reaching eol).

**Comment by edmorley** [comment]
@quentinlesceller Hi! Sorry for the delayed reply - the GitHub issues here have been mostly best effort (something I hope to improve as I catch up on the buildpack backlog). For guaranteed response times I would recommend filing a ticket at https://help.heroku.com/

Coincidentally I was taking a look at this issue yesterday - I found that a subset of the Cedar-14 runtime binaries had been compiled without `sqlite3` stdlib support (the switch to Ubuntu ESM meant the deploy method for Cedar-14 was changed, and the `libsqlite3-dev` package was missing in that environment).

I've since rebuilt those binaries with working sqlite support, and am going to update the build scripts to prevent the build from being marked as successful if one of the optional stdlibs wasn't built (by default the Python compile ignores missing packages and skips the module). I'm also going to expand the test matrix to cover more Python runtime patch versions, to prevent variations between them.
