### ISSUE TITLE
Config with static.json like in other buildpacks?

### ISSUE THREAD

**Issue by lggwettmann** [heroku/heroku-buildpack-python#975]
Hey guys, 

how do I configure nginx with this buildpack? I know in other buildpacks, they use a file called ```static.json``` where you can configure your Nginx set-up like this 
```
 {
   "https_only": true,
   "max_body_size": "10m"
 }
```

Is there any way to do this in this buildpack as well? I couldn't find anything in the documentation and issues.

**Comment by edmorley** [comment]
Hi @lggwettmann :-)

The Language buildpacks typically don't ship with nginx/apache (with the exception of the PHP buildpack), since most languages typically have their own more specialised web server (eg gunicorn in the case of Python), and with the [Heroku router](https://devcenter.heroku.com/articles/http-routing) fronting them with a reverse proxy is not normally necessary.

However if you'd like to use nginx, you can add an additional buildpack alongside the Python buildpack ([docs for multiple buildpacks](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app)), such as:
* [heroku-buildpack-static](https://github.com/heroku/heroku-buildpack-static) (simpler config via a `static.json` file, but slightly less customisable, and the buildpack isn't as maintained as the one below)
* [heroku-buildpack-nginx](https://github.com/heroku/heroku-buildpack-nginx)

That said, depending on your use-case it something other than nginx might be preferable, for example if using Django then I would recommend WhiteNoise - see: 
https://devcenter.heroku.com/articles/django-assets

Could you explain a bit more about the use-case?

**Comment by lggwettmann** [comment]
Hey @edmorley,

thanks so much for your kind and detailed answer. I'm using this heroku-buildpack to run a Django project in a Dokku instance. I only need to change the max body size of upload and deactivate HTTP routing, so writing a complete sigil-template for a new Nginx config would be a bit overkill, but doable. 

I just started using Dokku to deploy at some point and specified this buildpack only and it works great. We're serving static-files through Amazon S3, so no need for whitenoise. I'm not sure why or if we're using Nginx and gunicorn to be honest. 

I guess I was just looking for an easier and more DRY way to config our Nginx server - and assumed it was possible with such a config file too. Looks like I'll have to take a closer look at what Dokku is doing and how to do the Nginx config there.

Thanks for your time!

**Comment by edmorley** [comment]
@lggwettmann you're welcome! Thank you for the extra context.
I'll close this out for now, but feel free to reopen if you have any follow-up questions :-)
