### ISSUE TITLE
Heroku python buildpack error

### ISSUE THREAD

**Issue by Shadow101Dork** [heroku/heroku-buildpack-python#985]
I attempted to run the code `git push heroku master` and this was the output I received,
```
C:\Users\123\Desktop\Mysite\Webpage>git push heroku master
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 4 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (13/13), 1.77 KiB | 907.00 KiB/s, done.
Total 13 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/python.tgz
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to adithyad.
remote:
To https://git.heroku.com/adithyad.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/adithyad.git'
```

The defult detection failed, so I tried using the defult heroku python buildpack.That too didn't work.

Could someone help me ?

**Comment by edmorley** [comment]
@Shadow101Dork Hi! Sorry for the delayed reply, I was on vacation. For faster replies, I'd recommend opening a ticket at https://help.heroku.com since there is always support coverage there.

Could you list the files in the root of the repository you're git pushing? It looks like you are using Windows, so this can be performed by running `dir` from the repository root.

**Comment by edmorley** [comment]
Closing since this is a support issue. If you are still having this problem please open a ticket at https://help.heroku.com/ :-)
